import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-white dark:bg-black">

          {/* Sticky Navigation */}
          <header className="sticky top-0 z-50 border-b border-zinc-200 bg-white/80 backdrop-blur px-20 py-6 dark:border-zinc-800 dark:bg-black/80">
            <div className="flex items-center justify-between">
              <a
                className="text-lg font-semibold text-zinc-950 dark:text-zinc-50 hover:opacity-80"
                href="/"
              >
                Guangyu Liang
              </a>

              <nav className="flex gap-8 text-base text-zinc-700 dark:text-zinc-300">
                <a
                  className="hover:text-zinc-950 dark:hover:text-zinc-50"
                  href="/projects"
                >
                  Projects
                </a>

                <a
                  className="hover:text-zinc-950 dark:hover:text-zinc-50"
                  href="/CV"
                >
                  CV
                </a>

                <a
                  className="hover:text-zinc-950 dark:hover:text-zinc-50"
                  href="/contact"
                >
                  Contact
                </a>
              </nav>
            </div>
          </header>

          {/* Page Content */}
          <div className="px-20 pt-16 pb-10">
            <main>{children}</main>
          </div>

        </div>
      </body>
    </html>
  );
}